dist: trusty
sudo: false

notifications:
  slack: elbloquesemestrei:RKsDLWIhICKd5v7MmZlKwKnr

language: node_js
node_js:
  - "12"


cache:
  directories:
     - ./node_modules
     - ./coverage

install:
  - npm install


jobs:
  include:
  - stage: test
    script: apt-get -yq --no-install-suggests --allow-unauthenticated --no-install-recommends $(travis_apt_get_options) install google-chrome-stable
    script: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - stage: build
    before_script: skip
    install: skip
    script: npm run build --prod