dist: trusty
sudo: false

language: node_js
node_js:
  - "12"

before_script:
  - sudo -E apt-get -yq --no-install-suggests --allow-unauthenticated --no-install-recommends $(travis_apt_get_options) install google-chrome-stable 
cache:
  directories:
     - ./node_modules
     - ./coverage

install:
  - npm install


jobs:
  include:
  - stage: test
    script: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - stage: build
    install: skip
    script: npm run build --prod