dist: trusty
sudo: false

notifications:
  slack: 
    rooms:
      - elbloquesemestrei:RKsDLWIhICKd5v7MmZlKwKnr
    template:
      - "%{repository_slug} (%{commit}) : %{message}"
      - "Build details: %{build_url}"
      - "Coverage log: http://altermx.website/%{branch}/release-%{commit}"

language: node_js
node_js:
  - "12"
  
cache:
  directories:
     - ./node_modules
     - ./www
     - ./firebase-deploy
     - package.json
     - firebase.json
     - .firebaserc

install:
  - npm install
  - npm install --prefix=./firebase-deploy firebase-tools

jobs:
  include:
  - stage: test
    script:
    - sudo -E apt-get -yq install lftp
    - sudo -E apt-get -yq --no-install-suggests --allow-unauthenticated --no-install-recommends $(travis_apt_get_options) install google-chrome-stable 
    - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    - lftp sftp://altefxyj:UV07XAyx80JW@ftp.altermx.website  -p 21098  -e "set ssl:verify-certificate no; set sftp:auto-confirm yes; mirror -R coverage/ public_html/logs/$TRAVIS_BRANCH/$(git rev-parse --short ${TRAVIS_COMMIT}); quit"
  - stage: build
    before_script: skip
    install: skip
    script: npm run build --prod
  - stage: deploy
    before_script: skip
    install: skip
    script: ./firebase-deploy/node_modules/.bin/firebase deploy --token='1//0fLly0WkGtteWCgYIARAAGA8SNwF-L9Ir2bzV2ulSprOJsFudv2Dt3ORSP3VYpkuHyIEGflnwID2EM7LHe18Ca6XbyTT0CF8SpP0'
stages:
  - test
  - name: build
    if: branch = staging
  - name: deploy
    if: branch = staging